### ISSUE TITLE
No pre-built download available

### ISSUE THREAD

**Issue by drakon64** [caddy-dns/lego-deprecated#11]
Expected behaviour:
Caddy can be downloaded from https://caddyserver.com/download with this plugin included

Actual behaviour:
The plugin isn't present. Trying to download using the URL https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Flego-deprecated returns an error saying
`github.com/caddy-dns/lego-deprecated is not a registered Caddy module package path`.

**Comment by mholt** [comment]
We don't really support this plugin anymore due to its deprecated status. It also takes so many resources to build that it hogs our build server. So you can build.it from source if you want to, but it's not available on our site. Sorry!
