### ISSUE TITLE
What's an example of "provider code"? How do I know which ENVs to set?

### ISSUE THREAD

**Issue by coolaj86** [caddy-dns/lego-deprecated#3]
I'm trying to get this to work with dnsimple. How do I find out the "provider code" for it? Or its ENVs?

**Comment by mholt** [comment]
Hey AJ! Good question, if you follow the link to [the lego documentation](https://go-acme.github.io/lego/dns/) you'll find your provider in the ilst, then click it. Then you'll see the "code" there. For example, if your provider is Cloudflare:

<img width="832" alt="Screen Shot 2022-02-12 at 9 42 43 PM" src="https://user-images.githubusercontent.com/1128849/153739037-f228c075-d706-48a1-ab93-119917104cec.png">

Hope that helps :)

(but if it's cloudflare, obviously use the [caddy-dns/cloudflare](https://github.com/caddy-dns/cloudflare) package instead... so maybe not the best example, oh well)
