### ISSUE TITLE
Caddy with lego-deprecated plugin attempts to solve LE challenge for a domain that's not mine?

### ISSUE THREAD

**Issue by jfrederickson** [caddy-dns/lego-deprecated#5]
Hi - I just downloaded a copy of caddy with the lego-deprecated plugin. (Linode hosts my DNS, and there's not a native plugin for Caddy yet it seems.) It seems to have worked, and my own sites are served via HTTPS successfully but... my Caddy instance also seems to be trying to request certs for domains that aren't my own? I've got a bunch of these in my Caddy logs:

```
Mar 11 16:04:16 compute1.terracrypt.net caddy[10890]: {"level":"error","ts":1647014656.5855052,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"a1.hipaabank.org","error":"no information found to solve challenge for identifier: a1.hipaabank.org"}
Mar 11 16:04:16 compute1.terracrypt.net caddy[10890]: {"level":"error","ts":1647014656.5855882,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"a1.hipaabank.org","error":"no information found to solve challenge for identifier: a1.hipaabank.org"}
Mar 11 16:04:16 compute1.terracrypt.net caddy[10890]: {"level":"error","ts":1647014656.5930107,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"api.myhipaabank.com","error":"no information found to solve challenge for identifier: api.myhipaabank.com"}
Mar 11 16:04:16 compute1.terracrypt.net caddy[10890]: {"level":"error","ts":1647014656.593095,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"api.myhipaabank.com","error":"no information found to solve challenge for identifier: api.myhipaabank.com"}
```

But that's not my site! My Caddyfile is:

```
sandstorm.terracrypt.net {
	reverse_proxy 127.0.0.1:6080
	tls {
		dns lego_deprecated linode
	}
}

*.sandstorm.terracrypt.net {
	reverse_proxy 127.0.0.1:6080
	tls {
		dns lego_deprecated linode
	}
}

phillymud.net {
	reverse_proxy 10.224.130.171:4001
	tls {
		dns lego_deprecated linode
	}
}
```

This is... concerning, to say the least.

**Comment by mholt** [comment]
It has nothing to do with this plugin. It just means some remote server made an ACME challenge request to your server. There's nothing you can really do about that, since the remote servers are out of your control, it's basically spam traffic like any other.

Maybe the server is reusing an IP and a CA is still trying to verify the challenge from a previous tenant. :man_shrugging: In any case I wouldn't worry about it.

**Comment by jfrederickson** [comment]
Ah! Thanks for the clarification - it's my first time using Caddy, I guess I wasn't used to a web server having built-in ACME support yet so I didn't expect to see ACME logs when I wasn't trying to get a cert issued. Sorry for the noise :)

**Comment by mholt** [comment]
No worries. Welcome to Caddy, hope you like using it!

PS. Would love to see more Linode customers using Caddy :smiley:
