### ISSUE TITLE
Plugin not compiling on https://caddyserver.com/download

### ISSUE THREAD

**Issue by danielband** [caddy-dns/lego-deprecated#7]
Actual behavior:
When building over caddyserver.com the following error is thrown. With xcaddy the module builds without problems.
`
A plugin is not compiling. The developer must release a new version that compiles.
The build configuration is invalid. If you specified any versions, make sure they are correct and within the same major version as the path of the associated package.
`

Expected behavior:
Caddy should be bundled with this module and the user able to download.

**Comment by mholt** [comment]
Currently investigating this. Seems weird: https://twitter.com/mholt6/status/1544408394835976193

**Comment by mholt** [comment]
I got it to work today. Let me know if you still have problems.
